spring:
  application:
    name: noteverso
  datasource:
    url: jdbc:postgresql://localhost:5432/noteverso
    username: postgres
    password: byj6696@postgres.14
  output:
    ansi:
      enabled: always
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /noteverso/swagger
    tagsSorter: alpha
    filter: true
  api-docs:
    path: /noteverso/api-docs

logging:
  level:
    root: INFO
  file:
    path: ./logs

noteverso:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://api.noteverso.com/docs
