spring:
  port: 8080
  application:
    name: noteverso
    version: 0.0.1-SNAPSHOT
  output:
    ansi:
      enabled: always
springdoc:
  swagger-ui:
    path: /noteverso/swagger
    tryItOutEnable: true
    tagsSorter: alpha
    filter: true
  api-docs:
    path: /noteverso/api-docs

logging:
  path: ./logs
  level:
    root: INFO

noteverso:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://api.noteverso.com/docs
