export const PROJECT_COLORS = [
  { name: 'Berry Red', value: 'berry_red' },
  { name: 'Read', value: 'red' },
  { name: 'Orange', value: 'orange' },
  { name: 'Yellow', value: 'yellow' },
  { name: 'Olive Green', value: 'olive_green' },
  { name: 'Lime Green', value: 'lime_green' },
  { name: 'Green', value: 'green' },
  { name: 'Mint Green', value: 'mint_green' },
  { name: 'Teal', value: 'teal' },
  { name: 'Sky Blue', value: 'sky_blue' },
  { name: 'Light Blue', value: 'light_blue' },
  { name: 'Blue', value: 'blue' },
  { name: 'Grape', value: 'grape' },
  { name: 'Violet', value: 'violet' },
  { name: 'Lavender', value: 'lavender' },
  { name: 'Magenta', value: 'magenta' },
  { name: 'Salmon', value: 'salmon' },
  { name: 'Charcoal', value: 'charcoal' },
  { name: 'Grey', value: 'grey' },
  { name: 'Taupe', value: 'taupe' },
] as const

