name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [lts/*]
      fail-fast: false

    if: github.repository == 'Noteverso/app'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: './frontend/web/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd frontend/web
          pnpm install --frozen-lockfile

      - name: 🔎 Check code lint
        run: | 
          cd frontend/web
          pnpm lint

      - name: 🚀 Build the project
        run: |
          cd frontend/web
          pnpm build

      - name: ✅ Verify build output
        shell: bash
        run: |
          if [ ! -d ".frontend/web/dist" ]; then
            echo "Build failed: dist directory not found."
            exit 1
          else
            echo "Build succeeded! 🎉"
          fi
